services:
  mux:
    volumes:
      - ./configs/mode_b/test.mux:/configs/test.mux:ro

  mod:
    volumes:
      - ./configs/mode_b/ports25_mod.ini:/configs/ports25_mod.ini:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
