
server {
    
    listen 80 default_server;

    server_name _;
    
    location /nginx_status {
         stub_status;
            #allow 127.0.0.1;    #only allow requests from localhost or horizon
            #deny all;       #deny all other hosts   
    }
    
    root /usr/share/nginx/html;
    
    location / {
         index index.html index.htm;
     }
     
    location = /stats/mux {
         try_files /stats_mux.json =404;
    }
   
    location = /stats/mod {
         try_files /stats_mod.json =404;
    }
   
    location = /health {
         try_files /health.json =404;
    }

}

